defaults:
  - NPO

handler: NPOWithSurgery
method_args:
  # Gradient Surgery parameters (NPO parameters are inherited)
  surgery_strategy: "sago"  # ["sago", "sago_prefer_retain", "pcgrad", "pcgrad_global", "sum"]